In [ ]:
import numpy as np
# create an array from python list (1D)
list1=[1,2,3,4,5]
arr=np.array(list1)
print(arr)

In [2]:
# create a 2D array(matrix)array
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [3]:
# check the shap of the array
arr2=np.shape(arr)
print(arr2)

(2, 3)


In [5]:
# check the data type of array elements
print('data type of the array',arr.dtype)

data type of the array int64


In [6]:
# Reshape a 1D array of size 9 into a 3x3 matrix
arr=np.array([1,2,3,4,5,6,7,8,9])
reshape_arr=arr.reshape(3,3)
print(reshape_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
#Access the element at row2,column 3 in a 2D array.
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])

print(arr[1,2])

60


In [9]:
# Replace a specific element in a 2D array

np.put(arr,5,999)
print(arr)

[[ 10  20  30]
 [ 40  50 999]
 [ 70  80  90]]


In [32]:
# Slice the first two rows and columns of a 3 x 3 matrix

print(arr[:2])

[[1 2 3]
 [4 5 6]]


In [12]:
# Add two arrays element-wise
arr=np.array([1,2,3])
arr1=np.array([4,5,6])
result=arr+arr1
print(result)

[5 7 9]


In [ ]:
# Mutiply two arrays element-wise
arr=np.array([1,2,3])
arr1=np.array([4,5,6])
result=arr*arr1
print(result)

[ 4 10 18]


In [15]:
# Square every element in an array
arr=np.array([1,2,3])
result=arr**2
print(result)

[1 4 9]


In [18]:
# Find the sum of all elements in an array
arr=np.array([1,2,3,4,5])
result=arr.sum()
print(result)


15


In [23]:
# Create an array of 5 random integers between 1 and 10
arr=np.random.randint(1,11,5)
print(arr)

[ 1  2  5 10  9]


In [24]:
# Shuffle a Numpy array
arr=np.array([1,2,3,4,5])
np.random.shuffle(arr)
print(arr)

[5 2 3 4 1]


In [25]:
# Generate 1000 random number and find the mean
arr=np.random.rand(1000)
mean_value=arr.mean()
print(mean_value)

0.49554127813680265


In [26]:
# sort array in ascending order
arr=np.array([3,1,4,5,2])

result = np.sort(arr)
print(result)

[1 2 3 4 5]


In [29]:
# Search specific element in array

arr = np.array([10,20,30,40,50])
print(arr[2])

30


In [30]:
# Filter an array by even number
arr=np.array([1,2,3,4,5,6])
even_num=arr[arr % 2==0]
print(even_num)

[2 4 6]


In [ ]:
# Create 3 x 3 matrix and iterate matrix thro for loop

arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
for i in arr:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
9
