In [22]:
import pandas as pd
import numpy as np
df=pd.read_csv('student_admission_dataset.csv')
df

GPA  SAT_Score  Extracurricular_Activities Admission_Status
0    3.46       1223                           8         Rejected
1    2.54        974                           8         Rejected
2    2.91        909                           9         Rejected
3    2.83       1369                           5         Accepted
4    3.60       1536                           7         Accepted
..    ...        ...                         ...              ...
245  3.57       1024                           3         Rejected
246  2.86       1367                           1       Waitlisted
247  3.09       1036                           3       Waitlisted
248  3.51       1375                           5       Waitlisted
249  2.95       1583                           1       Waitlisted

[250 rows x 4 columns]

In [23]:
df.isnull().sum()
df

# df['Age'].fillna(df['Age'].mean(),inplace=True)

GPA  SAT_Score  Extracurricular_Activities Admission_Status
0    3.46       1223                           8         Rejected
1    2.54        974                           8         Rejected
2    2.91        909                           9         Rejected
3    2.83       1369                           5         Accepted
4    3.60       1536                           7         Accepted
..    ...        ...                         ...              ...
245  3.57       1024                           3         Rejected
246  2.86       1367                           1       Waitlisted
247  3.09       1036                           3       Waitlisted
248  3.51       1375                           5       Waitlisted
249  2.95       1583                           1       Waitlisted

[250 rows x 4 columns]

In [24]:
x=df.iloc[:,0:3].values
x

array([[3.460e+00, 1.223e+03, 8.000e+00],
       [2.540e+00, 9.740e+02, 8.000e+00],
       [2.910e+00, 9.090e+02, 9.000e+00],
       [2.830e+00, 1.369e+03, 5.000e+00],
       [3.600e+00, 1.536e+03, 7.000e+00],
       [3.520e+00, 1.476e+03, 9.000e+00],
       [3.840e+00, 1.002e+03, 8.000e+00],
       [2.630e+00, 9.750e+02, 6.000e+00],
       [3.130e+00, 1.450e+03, 8.000e+00],
       [2.540e+00, 1.118e+03, 7.000e+00],
       [2.830e+00, 1.418e+03, 2.000e+00],
       [3.260e+00, 1.171e+03, 7.000e+00],
       [2.540e+00, 1.035e+03, 7.000e+00],
       [2.800e+00, 1.257e+03, 4.000e+00],
       [3.470e+00, 9.700e+02, 3.000e+00],
       [3.320e+00, 1.150e+03, 1.000e+01],
       [2.830e+00, 1.278e+03, 4.000e+00],
       [3.380e+00, 1.191e+03, 8.000e+00],
       [3.710e+00, 1.061e+03, 7.000e+00],
       [2.510e+00, 1.348e+03, 1.000e+01],
       [3.710e+00, 1.456e+03, 3.000e+00],
       [3.550e+00, 1.209e+03, 4.000e+00],
       [3.010e+00, 1.526e+03, 7.000e+00],
       [2.730e+00, 1.569e+03, 1.00

In [25]:
y=df.iloc[:,3].values
y

array(['Rejected', 'Rejected', 'Rejected', 'Accepted', 'Accepted',
       'Accepted', 'Rejected', 'Waitlisted', 'Waitlisted', 'Rejected',
       'Rejected', 'Rejected', 'Rejected', 'Waitlisted', 'Accepted',
       'Accepted', 'Waitlisted', 'Accepted', 'Waitlisted', 'Accepted',
       'Waitlisted', 'Accepted', 'Rejected', 'Rejected', 'Accepted',
       'Waitlisted', 'Accepted', 'Accepted', 'Rejected', 'Waitlisted',
       'Rejected', 'Accepted', 'Rejected', 'Waitlisted', 'Accepted',
       'Accepted', 'Rejected', 'Waitlisted', 'Waitlisted', 'Waitlisted',
       'Waitlisted', 'Waitlisted', 'Accepted', 'Accepted', 'Waitlisted',
       'Waitlisted', 'Accepted', 'Accepted', 'Waitlisted', 'Waitlisted',
       'Accepted', 'Rejected', 'Rejected', 'Rejected', 'Accepted',
       'Accepted', 'Accepted', 'Rejected', 'Waitlisted', 'Accepted',
       'Accepted', 'Accepted', 'Rejected', 'Waitlisted', 'Rejected',
       'Rejected', 'Rejected', 'Accepted', 'Rejected', 'Waitlisted',
       'Waitlisted',

In [26]:
from sklearn.preprocessing import LabelEncoder
Labelencoder_y=LabelEncoder()
y=Labelencoder_y.fit_transform(y)
y

array([1, 1, 1, 0, 0, 0, 1, 2, 2, 1, 1, 1, 1, 2, 0, 0, 2, 0, 2, 0, 2, 0,
       1, 1, 0, 2, 0, 0, 1, 2, 1, 0, 1, 2, 0, 0, 1, 2, 2, 2, 2, 2, 0, 0,
       2, 2, 0, 0, 2, 2, 0, 1, 1, 1, 0, 0, 0, 1, 2, 0, 0, 0, 1, 2, 1, 1,
       1, 0, 1, 2, 2, 2, 2, 1, 2, 2, 1, 1, 0, 1, 1, 0, 0, 1, 0, 2, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 2, 2, 1, 1, 2, 2, 0, 0, 2, 1, 2, 1, 2, 0, 1,
       0, 2, 1, 1, 1, 0, 2, 0, 1, 0, 1, 0, 2, 0, 0, 0, 0, 2, 1, 1, 1, 2,
       2, 0, 2, 1, 2, 1, 2, 2, 1, 1, 2, 2, 0, 1, 0, 2, 1, 2, 1, 2, 0, 0,
       0, 1, 1, 1, 0, 1, 2, 1, 0, 0, 2, 1, 1, 2, 2, 0, 1, 2, 1, 2, 0, 2,
       2, 2, 2, 2, 1, 0, 0, 2, 2, 1, 2, 2, 1, 2, 1, 0, 2, 0, 2, 2, 2, 0,
       2, 1, 0, 1, 1, 2, 2, 0, 0, 1, 2, 1, 2, 1, 2, 0, 0, 2, 1, 0, 2, 2,
       1, 2, 0, 0, 1, 1, 0, 1, 0, 2, 1, 0, 1, 2, 0, 0, 0, 2, 0, 1, 0, 2,
       1, 2, 1, 1, 2, 2, 2, 2])

In [27]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [28]:
from sklearn.linear_model import LogisticRegression
logmodel=LogisticRegression()
logmodel.fit(x_train,y_train)

c:\Users\sonaw\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:470: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [29]:
y_pred=logmodel.predict(x_test)
y_pred


array([2, 1, 2, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 2, 2, 2, 2, 0, 1, 2,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 2, 0, 0, 2, 0, 1, 1, 1, 0, 0, 2, 0, 0,
       0, 2, 0, 2, 2, 1])

In [30]:
y_pred=logmodel.predict(x_test)
y_pred

array([2, 1, 2, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 2, 2, 2, 2, 0, 1, 2,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 2, 0, 0, 2, 0, 1, 1, 1, 0, 0, 2, 0, 0,
       0, 2, 0, 2, 2, 1])

In [31]:
y_test

array([2, 2, 1, 0, 1, 0, 0, 0, 2, 0, 0, 1, 0, 2, 2, 0, 1, 1, 0, 1, 1, 1,
       1, 2, 2, 2, 2, 1, 2, 1, 0, 2, 0, 2, 1, 2, 0, 1, 1, 0, 2, 2, 2, 0,
       1, 2, 0, 2, 1, 2])

In [32]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)


array([[11,  1,  3],
       [ 3,  6,  7],
       [11,  3,  5]])

In [33]:
from sklearn.neighbors import KNeighborsClassifier
classifier_knn=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
classifier_knn.fit(x_train,y_train)

KNeighborsClassifier()

In [34]:
y_pred=classifier_knn.predict(x_test)

In [35]:
y_pred

array([0, 1, 1, 2, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 1, 2, 0, 2, 1, 2, 0, 0,
       2, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 2, 2, 0, 1, 1, 0, 2,
       0, 0, 0, 1, 2, 0])

In [37]:

gpa=float(input('Enter the gpa:'))
sat_score=int(input('Enter the SAT_Score:'))
activities=int(input('Enter the activites :'))

predicted=logmodel.predict([[gpa,sat_score,activities]])
print(f"admission status:{predicted}")

admission status:[1]
